// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// optimal_transport_sinkhorn
List optimal_transport_sinkhorn(Eigen::MatrixXd costMatrix, int numIterations, double epsilon);
RcppExport SEXP _gsaot_optimal_transport_sinkhorn(SEXP costMatrixSEXP, SEXP numIterationsSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type costMatrix(costMatrixSEXP);
    Rcpp::traits::input_parameter< int >::type numIterations(numIterationsSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(optimal_transport_sinkhorn(costMatrix, numIterations, epsilon));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gsaot_optimal_transport_sinkhorn", (DL_FUNC) &_gsaot_optimal_transport_sinkhorn, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_gsaot(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
