# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sinkhorn <- function(a, b, costm, numIterations, epsilon, maxErr) {
    .Call(`_gsaot_sinkhorn`, a, b, costm, numIterations, epsilon, maxErr)
}

sinkhorn_stable <- function(a, b, costm, numIterations, epsilon, maxErr, tau) {
    .Call(`_gsaot_sinkhorn_stable`, a, b, costm, numIterations, epsilon, maxErr, tau)
}

